#Multiples of 3 or 5
#Problem 1

#If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
#Find the sum of all the multiples of 3 or 5 below 1000.

p1_sum = 0
for num in list(range(3, 1000)):
    if num % 3 == 0 or num % 5 == 0:
        p1_sum += num

print(p1_sum)

#Even Fibonacci numbers
#Problem 2

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


p2_sum = 0
p2_current_fib = 2
p2_current_index = 1
p2_previous_index = 0
p2_fib_sequence = [1, 2]

while p2_current_fib < 4000000:
    p2_fib_sequence.append(p2_fib_sequence[p2_current_index] + p2_fib_sequence[p2_previous_index])
    p2_current_fib += p2_fib_sequence[p2_previous_index]
    p2_current_index += 1
    p2_previous_index += 1

for num in p2_fib_sequence:
    if num % 2 == 0:
        p2_sum += num

print(p2_sum)
print(p2_fib_sequence)